name: tests

on:
  push:
  pull_request_target:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: |
        sudo apt-get install --yes -qq build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r)
        sudo apt-get install --yes -qq zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev python-dev python-setuptools python-cffi python3 python3-dev python3-setuptools python3-cffi
        # packages for tests
        sudo apt-get install --yes -qq parted lsscsi ksh attr acl nfs-kernel-server fio
    - name: Prepare
      run: |
        sh autogen.sh
        ./configure --enable-debug --enable-debuginfo
        make --no-print-directory deb-kmod pkg-utils
        sudo dpkg -i *.deb
    - name: Tests
      run: |
        /usr/share/zfs/zfs-tests.sh -v
    - name: Echo results
      if: ${{ failure() }}
      run: |
        find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cat {} \;
