name: tests

on:
  push:
  pull_request_target:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes -qq build-essential autoconf libtool gdb lcov
        sudo apt-get install --yes -qq git alien fakeroot wget curl bc fio acl \
          sysstat mdadm lsscsi parted gdebi attr dbench watchdog ksh \
          nfs-kernel-server samba rng-tools xz-utils dkms
        sudo apt-get install --yes -qq linux-headers-$(uname -r) \
          zlib1g-dev uuid-dev libblkid-dev libselinux-dev \
          xfslibs-dev libattr1-dev libacl1-dev libudev-dev libdevmapper-dev \
          libssl-dev libffi-dev libaio-dev libelf-dev libmount-dev \
          libpam0g-dev pamtester python-dev python-setuptools python-cffi \
          python3 python3-dev python3-setuptools python3-cffi
    - name: Prepare
      run: |
        sh autogen.sh
        ./configure --enable-debug --enable-debuginfo
        make --no-print-directory deb-kmod pkg-utils
        sudo dpkg -i *.deb
    - name: Tests
      run: |
        /usr/share/zfs/zfs-tests.sh -v -T l2arc
    - name: Echo results
      if: ${{ always() }}
      run: |
        find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cat {} \;
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Test logs
        path: /var/tmp/test_results/current/
        if-no-files-found: ignore
